-- MySQL Script generated by MySQL Workbench
-- 07/28/17 22:19:56
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema redesocial
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema redesocial
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `redesocial` DEFAULT CHARACTER SET utf8 ;
USE `redesocial` ;

-- -----------------------------------------------------
-- Table `redesocial`.`albuns`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `redesocial`.`albuns` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `data` DATETIME NULL,
  `usuario` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Albuns_Usuarios_idx` (`usuario` ASC),
  CONSTRAINT `fk_Albuns_Usuarios`
    FOREIGN KEY (`usuario`)
    REFERENCES `redesocial`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `redesocial`.`multimidias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `redesocial`.`multimidias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `midia` BLOB NULL,
  `tipo_conteudo` VARCHAR(20) NULL,
  `data` DATETIME NULL,
  `album` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Multimidias_Albuns1_idx` (`album` ASC),
  CONSTRAINT `fk_Multimidias_Albuns1`
    FOREIGN KEY (`album`)
    REFERENCES `redesocial`.`albuns` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `redesocial`.`paises`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `redesocial`.`paises` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(90) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `redesocial`.`estados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `redesocial`.`estados` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(90) NULL,
  `pais` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Estados_Paises1_idx` (`pais` ASC),
  CONSTRAINT `fk_Estados_Paises1`
    FOREIGN KEY (`pais`)
    REFERENCES `redesocial`.`paises` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `redesocial`.`cidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `redesocial`.`cidades` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(90) NULL,
  `estado` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Cidades_Estados1_idx` (`estado` ASC),
  CONSTRAINT `fk_Cidades_Estados1`
    FOREIGN KEY (`estado`)
    REFERENCES `redesocial`.`estados` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `redesocial`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `redesocial`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(200) NOT NULL,
  `email` VARCHAR(200) NOT NULL,
  `telefone` VARCHAR(18) NULL,
  `senha` CHAR(32) NOT NULL,
  `nascimento` DATE NOT NULL,
  `sexo` CHAR(1) NOT NULL,
  `data_cadastro` DATETIME NULL,
  `status` TINYINT(1) NULL DEFAULT 1,
  `foto` INT NOT NULL,
  `cidade` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Usuarios_Multimidias1_idx` (`foto` ASC),
  INDEX `fk_Usuarios_Cidades1_idx` (`cidade` ASC),
  CONSTRAINT `fk_Usuarios_Multimidias1`
    FOREIGN KEY (`foto`)
    REFERENCES `redesocial`.`multimidias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuarios_Cidades1`
    FOREIGN KEY (`cidade`)
    REFERENCES `redesocial`.`cidades` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `redesocial`.`postagens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `redesocial`.`postagens` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `curtidas` INT NULL,
  `descricao` TEXT NULL,
  `data` DATETIME NULL,
  `usuario` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_postagens_usuarios1_idx` (`usuario` ASC),
  CONSTRAINT `fk_postagens_usuarios1`
    FOREIGN KEY (`usuario`)
    REFERENCES `redesocial`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `redesocial`.`comentarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `redesocial`.`comentarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` TEXT NULL,
  `curtidas` INT NULL,
  `data` DATETIME NULL,
  `postagem` INT NOT NULL,
  `resposta` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Comentarios_Postagens1_idx` (`postagem` ASC),
  INDEX `fk_Comentarios_Comentarios1_idx` (`resposta` ASC),
  CONSTRAINT `fk_Comentarios_Postagens1`
    FOREIGN KEY (`postagem`)
    REFERENCES `redesocial`.`postagens` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comentarios_Comentarios1`
    FOREIGN KEY (`resposta`)
    REFERENCES `redesocial`.`comentarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `redesocial`.`postagens_multimidas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `redesocial`.`postagens_multimidas` (
  `postagem` INT NOT NULL,
  `multimidia` INT NOT NULL,
  PRIMARY KEY (`postagem`, `multimidia`),
  INDEX `fk_Postagens_has_Multimidias_Multimidias1_idx` (`multimidia` ASC),
  INDEX `fk_Postagens_has_Multimidias_Postagens1_idx` (`postagem` ASC),
  CONSTRAINT `fk_Postagens_has_Multimidias_Postagens1`
    FOREIGN KEY (`postagem`)
    REFERENCES `redesocial`.`postagens` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Postagens_has_Multimidias_Multimidias1`
    FOREIGN KEY (`multimidia`)
    REFERENCES `redesocial`.`multimidias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `redesocial`.`postagens_albuns`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `redesocial`.`postagens_albuns` (
  `postagem` INT NOT NULL,
  `album` INT NOT NULL,
  PRIMARY KEY (`postagem`, `album`),
  INDEX `fk_Postagens_has_Albuns_Albuns1_idx` (`album` ASC),
  INDEX `fk_Postagens_has_Albuns_Postagens1_idx` (`postagem` ASC),
  CONSTRAINT `fk_Postagens_has_Albuns_Postagens1`
    FOREIGN KEY (`postagem`)
    REFERENCES `redesocial`.`postagens` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Postagens_has_Albuns_Albuns1`
    FOREIGN KEY (`album`)
    REFERENCES `redesocial`.`albuns` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
